### ISSUE TITLE
Chat bridge between Discord and Minecraft

### ISSUE THREAD

**Issue by DinoMarlir** [EinfachGustaf/SMPv2#10]
<img width="611" alt="image" src="https://github.com/DinoMarlir/einfachgustaf-smp/assets/72864666/b5586006-749e-4f6a-a025-53f8e040831d">

**Comment by mathearbeit76** [comment]
DiscordSRV is only available for Paper servers.
I would recommend [Discord-MC-Chat](https://modrinth.com/mod/discord-mc-chat) or [Discord Integration](https://modrinth.com/plugin/dcintegration) instead. Both support webhooks.

**Comment by DinoMarlir** [comment]
Done in #63
