### ISSUE TITLE
Feature abstraction to enable/disable features

### ISSUE THREAD

**Issue by DinoMarlir** [EinfachGustaf/SMPv2#8]
**Is your feature request related to a problem? Please describe.**
There is no way to enable/disable features.

**Describe the solution you'd like**
Provide a config file to disable or enable features

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by JulixnDev** [comment]
I take it. 
Do you mean that you can turn on/off features like the discord chatsync and so?

**Comment by DinoMarlir** [comment]
> I take it. Do you mean that you can turn on/off features like the discord chatsync and so?

@JulixnDev yes, this is exactly what I mean. :)
